{pkgs, ...}: {
  home.packages = with pkgs; [
    acpi
    alacritty
    arandr
    awesome
    brightnessctl
    btop
    #deezer
    gcc
    devbox
    pavucontrol
    dex
    discord
    easyeffects
    evdevremapkeys
    fastfetch
    git
    firefox
    firefox-devedition-bin
    flameshot
    frei0r
    gimp
    delta
    gnome.gnome-calculator
    gnome.gnome-keyring
    gvfs
    i3lock-fancy
    #interception-caps2esc
    #lain
    libreoffice-fresh
    lsd
    lsp-plugins
    lxappearance
    matcha-gtk-theme
    moar
    mpv
    neovim
    #network-manager-applet
    #npm
    papirus-icon-theme
    picom
    qtile
    redshift
    ripgrep
    xfce.ristretto
    rofi
    slack
    sxhkd
    home-manager
    xfce.thunar
    xfce.thunar-archive-plugin
    xfce.thunar-volman
    tmux
    transmission-gtk
    webp-pixbuf-loader
    wget
    xclip
    xorg.xrdb
    xss-lock
    zoxide
  ];
}
