{inputs, pkgs, ...}: {
  environment.systemPackages = with pkgs; [
    #deezer
    #interception-caps2esc
    #lain
    #network-manager-applet
    #npm
    acpi
    alacritty
    arandr
    autorandr
    awesome
    blueman
    brightnessctl
    btop
    delta
    devbox
    dex
    discord
    easyeffects
    evdevremapkeys
    fastfetch
    firefox
    firefox-devedition-bin
    flameshot
    frei0r
    gcc
    gimp
    git
    gnome.gnome-calculator
    gnome.gnome-keyring
    gvfs
    home-manager
    i3lock-fancy
    libreoffice-fresh
    lsd
    lsp-plugins
    lxappearance
    matcha-gtk-theme
    moar
    mpv
    neovim
    papirus-icon-theme
    pavucontrol
    picom
    qtile
    redshift
    ripgrep
    rofi
    slack
    sxhkd
    tmux
    transmission-gtk
    webp-pixbuf-loader
    wget
    xclip
    xfce.ristretto
    xfce.thunar
    xfce.thunar-archive-plugin
    xfce.thunar-volman
    xorg.xrdb
    xss-lock
    zoxide
  ];
}
